### PR TITLE
Cuda tromp should be default solver

### PR DESCRIPTION
**Pull request by renuzit**
This commit makes cuda tromp the default solver to hopefully lower the
barrier of entry for new miners.y

### CODE REVIEW

**Comment by egyptianbman** [comment]
Should this be changed? https://github.com/btcz/zhasher/blob/master/CMakeLists.txt#L8

**Comment by renuzit** [comment]
I wish it could be enabled, but it appears that CPU tromp and CUDA tromp can't live in the same binary together.

**Comment by cryptorex** [comment]
is this a Linux thing? - cause as far as I know for win64 it works - at least I seems to compile in and submit shares.

**Comment by renuzit** [comment]
Possibly? I haven't had time to really figure out what's going on with it.

**Review by egyptianbman — APPROVED** [review]

**Pull request merged**
